#!/bin/bash

cpt=${PWD##*/}          # to assign to a variable
cpt=${result:-/}        # to correct for the case where PWD=/
cpt=$(printf '%q\n' "${PWD##*/}")
cpt=${cpt,,}

rm -f /etc/nginx/sites-enabled/$cpt

echo "Stopping container"
docker rm -f $cpt 2>&1

echo "Reloading nginx"
nginx -t && nginx -s reload

echo ""
echo "Done"
echo ""
